Repository FS05-PART3-TEAM2/5-fav_photo-team2-fe, pull requests merged in 2025-03, with the labels that each got.

#24 chore: storybook 세팅
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  .storybook/vitest.setup.ts
  package-lock.json
  package.json
  src/stories/TailwindTest.stories.ts
  src/stories/TailwindTest.tsx
  tailwind.config.ts
  vitest.config.ts
Labels: task

#30 chore: husky 설치를 통한 git hook 설정
  .husky/pre-commit
  .prettierrc
  README.md
  package-lock.json
  package.json
Labels: task

#34 Feat/공통컴포넌트 카드요소(헤더, 상세)
  package-lock.json
  package.json
  src/components/common/card/CardDetail.stories.ts
  src/components/common/card/CardDetail.tsx
  src/components/common/card/CardHeader.stories.ts
  src/components/common/card/CardHeader.tsx
  src/components/common/card/PhotoCard.tsx
  src/styles/globals.css
  src/types/photocard.types.ts
Labels: feature

#35 fix: husky 오류 수정
  .husky/pre-commit
Labels: bug
